#!/usr/bin/env bash
set -euo pipefail

OUT=${OUT:-results/raw/wan_cutover.csv}
TABLE_OUT=${TABLE_OUT:-results/tables/wan_cutover.tex}
N=${N:-4}
F=${F:-1}
MAX_HEIGHT=${MAX_HEIGHT:-8}
H_D=${H_D:-2}
H_C=${H_C:-4}
H_R=${H_R:-8}
STRATEGY=${STRATEGY:-sage}
MAX_SECS=${MAX_SECS:-30}
RUN_NETEM=${RUN_NETEM:-0}

mkdir -p "$(dirname "$OUT")"

write_skip() {
  local reason=$1
  cat >"$OUT" <<CSV
profile,delay_ms,jitter_ms,loss_pct,strategy,n,f,max_height,cutover_height,migration_success,observed_fork,total_messages,run_status,skip_reason
skip,0,0,0,$STRATEGY,$N,$F,$MAX_HEIGHT,,false,false,0,skipped,$reason
CSV
  write_table
  echo "WAN netem skipped: $reason" >&2
}

write_table() {
  mkdir -p "$(dirname "$TABLE_OUT")"
  {
    echo '% Auto-generated by scripts/netem_wan_testbed.sh'
    echo '\begin{tabular}{lrrrr}'
    echo 'Profile & Delay ms & Loss \% & Cutover & Fork \\'
    echo '\midrule'
    tail -n +2 "$OUT" | while IFS=, read -r profile delay_ms jitter_ms loss_pct strategy n f max_height cutover_height migration_success observed_fork total_messages run_status skip_reason; do
      if [[ "$run_status" == "skipped" ]]; then
        echo "$profile & $delay_ms & $loss_pct & -- & skipped \\\\"
      else
        echo "$profile & $delay_ms & $loss_pct & ${cutover_height:---} & $observed_fork \\\\"
      fi
    done
    echo '\end{tabular}'
  } >"$TABLE_OUT"
}

if ! command -v tc >/dev/null 2>&1; then
  write_skip "tc-not-found"
  exit 0
fi
if [[ "$RUN_NETEM" != "1" ]]; then
  write_skip "set RUN_NETEM=1 to apply tc netem to loopback"
  exit 0
fi
if [[ ${EUID:-$(id -u)} -ne 0 ]]; then
  write_skip "requires-root-or-CAP_NET_ADMIN"
  exit 0
fi

cargo build -p sage-node --bin spawn_testbed --bin validator_proc
TMP=$(mktemp -d)
cleanup() {
  tc qdisc del dev lo root >/dev/null 2>&1 || true
  rm -rf "$TMP"
}
trap cleanup EXIT

cat >"$OUT" <<CSV
profile,delay_ms,jitter_ms,loss_pct,strategy,n,f,max_height,cutover_height,migration_success,observed_fork,total_messages,run_status,skip_reason
CSV

run_profile() {
  local profile=$1 delay=$2 jitter=$3 loss=$4
  local raw="$TMP/${profile}.csv"
  tc qdisc del dev lo root >/dev/null 2>&1 || true
  tc qdisc add dev lo root netem delay "${delay}ms" "${jitter}ms" loss "${loss}%"
  cargo run -p sage-node --bin spawn_testbed -- \
    --n "$N" --f "$F" --strategy "$STRATEGY" --max-height "$MAX_HEIGHT" \
    --h-d "$H_D" --h-c "$H_C" --h-r "$H_R" --max-secs "$MAX_SECS" --out "$raw"
  tail -n +2 "$raw" | while IFS=, read -r strategy n f validator migration_success max_finalized_height cutover_height observed_fork run_max_height total_duration_secs messages_sent total_messages replay_context_root replay_context_root_agreement replay_context_ok manifest_payload_hash manifest_payload_hash_agreement manifest_payload_ok; do
    printf '%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,ok,\n' \
      "$profile" "$delay" "$jitter" "$loss" "$strategy" "$n" "$f" "$run_max_height" \
      "$cutover_height" "$migration_success" "$observed_fork" "$total_messages" >>"$OUT"
  done
}

# Representative engineering buckets, not provider-specific measurements.
# Delay is configured as one-way loopback delay; approximate RTT is about 2x before host noise.
run_profile metro 10 2 0.0              # same-region / same-country profile
run_profile continental 50 10 0.1       # regional or continental WAN profile
run_profile intercontinental 120 25 0.5 # stressed global profile
run_profile adverse 200 50 1.0          # robustness stress, not a typical deployment claim
write_table

echo "Wrote WAN netem results to $OUT"
